server:
  port: 8282
  servlet:
    context-path: /employees
spring:
  application:
    name: employee
  datasource:
    url: jdbc:mariadb://localhost:3306/employees
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
app:
  security:
    api-key: my-demo-employee-api-key


